##########
# collectionbuilder-sheets
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-sheets
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-sheets

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Global Medieval and Early Modern Digital Library
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Medieval and Early Modern texts from around the globe translated into English.
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The Global Medieval and Early Modern Digital Library brings together translations, often accompanied by transcriptions, of primary sources encompassing a wide range of genres, regions and languages from the period between Late Antiquity and 1700. The site allows these sources to be organized by theme, region, language and date."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: upenndigitalscholarship


##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection 
# This will be the full URL to your CSV file or relative path + filename of CSV in this repository 
# e.g. relative path "/assets/demo-metadata.csv"
# e.g. published google sheet "https://docs.google.com/spreadsheets/d/e/2PACX-1vSPeYbfqxUs5cRalwTejAL4zgXfIraB9i__GmaJQ14cTAGx1CQQaDd1RFOVfmYkZ_QP7uJ2ISRZzQJS/pub?gid=1908577825&single=true&output=csv"
# e.g. on GitHub use the raw link "https://raw.githubusercontent.com/CollectionBuilder/collectionbuilder-sample-data/master/psychiana_cbdemo_gh.csv"
metadata-csv: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQBf-Kju6JGQkO1ibauCi6tWo3EJuPuPwLELw5o7L7sX-Mr8ZRonQAFbGA4xgOMwOU15KlO3Nh73pC5/pub?gid=1778110557&single=true&output=csv"

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
organization-name: "Center for Research Data and Digital Scholarship, Penn Libraries"
organization-link: https://www.library.upenn.edu/help-with/research-data-digital-scholarship
organization-logo-banner: '/assets/img/PennLibrariesLogo2020_BlackRGB.png'
organization-logo-nav: '/assets/img/PennLibrariesLogo2020_BlackRGB.png'


##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
#
development-refresh: true
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
